"""New fixes

Revision ID: abcdefghikjo
Revises: 66f72f04a1de
Create Date: 2024-01-26 13:34:14.496769

"""

from typing import Sequence, Union
import warnings

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = "abcdefghikjo"
down_revision: Union[str, None] = "66f72f04a1de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS pausedflow;")
    op.create_table('pausedflow',
    sa.Column('id', sqlmodel.sql.sqltypes.types.Uuid(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_id', sqlmodel.sql.sqltypes.types.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.types.Uuid(), nullable=False),
    sa.Column('graph_state', sa.JSON(), nullable=True),
    sa.Column('hitl_component_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_pausedflow_run_id'), 'pausedflow', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pausedflow_run_id'), table_name='pausedflow')
    op.drop_table('pausedflow')
    # ### end Alembic commands ###