"""add project request table v2

Revision ID: 8a7b6c5d4e3f
Revises: 07b81407d7ed
Create Date: 2024-03-19 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '8a7b6c5d4e3f'
down_revision: Union[str, None] = '07b81407d7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectrequest',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_name', sa.String(), nullable=False),
        sa.Column('justification', sa.String(), nullable=False),
        sa.Column('requested_users', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('rejection_reason', sa.String(), nullable=True),
        sa.Column('requester_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectrequest_project_name'), 'projectrequest', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projectrequest_project_name'), table_name='projectrequest')
    op.drop_table('projectrequest')
    # ### end Alembic commands ### 